package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 06 17:02:54 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MmpFarmerRegVerifImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FarmerRegVerifId,
        NameVerif,
        FatherName,
        Ast,
        Gender,
        ClusterId,
        BeneficiaryId,
        MarStatus,
        Dob,
        Doj,
        Ntn,
        PassNo,
        Cnic,
        DrLicNo,
        Telephone,
        Mobile,
        Email,
        Url,
        PreAddress,
        PerAddress,
        Image,
        FarmerNo,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        FarmerRegTehsil,
        FarmerRegDistrict,
        GrantStatus,
        MmpFarmerRegVerifLand,
        MmpFarmerRegDVerif;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FARMERREGVERIFID = AttributesEnum.FarmerRegVerifId.index();
    public static final int NAMEVERIF = AttributesEnum.NameVerif.index();
    public static final int FATHERNAME = AttributesEnum.FatherName.index();
    public static final int AST = AttributesEnum.Ast.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int CLUSTERID = AttributesEnum.ClusterId.index();
    public static final int BENEFICIARYID = AttributesEnum.BeneficiaryId.index();
    public static final int MARSTATUS = AttributesEnum.MarStatus.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int DOJ = AttributesEnum.Doj.index();
    public static final int NTN = AttributesEnum.Ntn.index();
    public static final int PASSNO = AttributesEnum.PassNo.index();
    public static final int CNIC = AttributesEnum.Cnic.index();
    public static final int DRLICNO = AttributesEnum.DrLicNo.index();
    public static final int TELEPHONE = AttributesEnum.Telephone.index();
    public static final int MOBILE = AttributesEnum.Mobile.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int URL = AttributesEnum.Url.index();
    public static final int PREADDRESS = AttributesEnum.PreAddress.index();
    public static final int PERADDRESS = AttributesEnum.PerAddress.index();
    public static final int IMAGE = AttributesEnum.Image.index();
    public static final int FARMERNO = AttributesEnum.FarmerNo.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int FARMERREGTEHSIL = AttributesEnum.FarmerRegTehsil.index();
    public static final int FARMERREGDISTRICT = AttributesEnum.FarmerRegDistrict.index();
    public static final int GRANTSTATUS = AttributesEnum.GrantStatus.index();
    public static final int MMPFARMERREGVERIFLAND = AttributesEnum.MmpFarmerRegVerifLand.index();
    public static final int MMPFARMERREGDVERIF = AttributesEnum.MmpFarmerRegDVerif.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MmpFarmerRegVerifImpl() {
    }

    /**
     * Gets the attribute value for FarmerRegVerifId, using the alias name FarmerRegVerifId.
     * @return the value of FarmerRegVerifId
     */
    public BigDecimal getFarmerRegVerifId() {
        return (BigDecimal) getAttributeInternal(FARMERREGVERIFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FarmerRegVerifId.
     * @param value value to set the FarmerRegVerifId
     */
    public void setFarmerRegVerifId(BigDecimal value) {
        setAttributeInternal(FARMERREGVERIFID, value);
    }

    /**
     * Gets the attribute value for NameVerif, using the alias name NameVerif.
     * @return the value of NameVerif
     */
    public String getNameVerif() {
        return (String) getAttributeInternal(NAMEVERIF);
    }

    /**
     * Sets <code>value</code> as the attribute value for NameVerif.
     * @param value value to set the NameVerif
     */
    public void setNameVerif(String value) {
        setAttributeInternal(NAMEVERIF, value);
    }

    /**
     * Gets the attribute value for FatherName, using the alias name FatherName.
     * @return the value of FatherName
     */
    public String getFatherName() {
        return (String) getAttributeInternal(FATHERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FatherName.
     * @param value value to set the FatherName
     */
    public void setFatherName(String value) {
        setAttributeInternal(FATHERNAME, value);
    }

    /**
     * Gets the attribute value for Ast, using the alias name Ast.
     * @return the value of Ast
     */
    public String getAst() {
        return (String) getAttributeInternal(AST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ast.
     * @param value value to set the Ast
     */
    public void setAst(String value) {
        setAttributeInternal(AST, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the value of Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for ClusterId, using the alias name ClusterId.
     * @return the value of ClusterId
     */
    public BigDecimal getClusterId() {
        return (BigDecimal) getAttributeInternal(CLUSTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClusterId.
     * @param value value to set the ClusterId
     */
    public void setClusterId(BigDecimal value) {
        setAttributeInternal(CLUSTERID, value);
    }

    /**
     * Gets the attribute value for BeneficiaryId, using the alias name BeneficiaryId.
     * @return the value of BeneficiaryId
     */
    public BigDecimal getBeneficiaryId() {
        return (BigDecimal) getAttributeInternal(BENEFICIARYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BeneficiaryId.
     * @param value value to set the BeneficiaryId
     */
    public void setBeneficiaryId(BigDecimal value) {
        setAttributeInternal(BENEFICIARYID, value);
    }

    /**
     * Gets the attribute value for MarStatus, using the alias name MarStatus.
     * @return the value of MarStatus
     */
    public String getMarStatus() {
        return (String) getAttributeInternal(MARSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarStatus.
     * @param value value to set the MarStatus
     */
    public void setMarStatus(String value) {
        setAttributeInternal(MARSTATUS, value);
    }

    /**
     * Gets the attribute value for Dob, using the alias name Dob.
     * @return the value of Dob
     */
    public Timestamp getDob() {
        return (Timestamp) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dob.
     * @param value value to set the Dob
     */
    public void setDob(Timestamp value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for Doj, using the alias name Doj.
     * @return the value of Doj
     */
    public Timestamp getDoj() {
        return (Timestamp) getAttributeInternal(DOJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Doj.
     * @param value value to set the Doj
     */
    public void setDoj(Timestamp value) {
        setAttributeInternal(DOJ, value);
    }

    /**
     * Gets the attribute value for Ntn, using the alias name Ntn.
     * @return the value of Ntn
     */
    public String getNtn() {
        return (String) getAttributeInternal(NTN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ntn.
     * @param value value to set the Ntn
     */
    public void setNtn(String value) {
        setAttributeInternal(NTN, value);
    }

    /**
     * Gets the attribute value for PassNo, using the alias name PassNo.
     * @return the value of PassNo
     */
    public String getPassNo() {
        return (String) getAttributeInternal(PASSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PassNo.
     * @param value value to set the PassNo
     */
    public void setPassNo(String value) {
        setAttributeInternal(PASSNO, value);
    }

    /**
     * Gets the attribute value for Cnic, using the alias name Cnic.
     * @return the value of Cnic
     */
    public String getCnic() {
        return (String) getAttributeInternal(CNIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cnic.
     * @param value value to set the Cnic
     */
    public void setCnic(String value) {
        setAttributeInternal(CNIC, value);
    }

    /**
     * Gets the attribute value for DrLicNo, using the alias name DrLicNo.
     * @return the value of DrLicNo
     */
    public String getDrLicNo() {
        return (String) getAttributeInternal(DRLICNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DrLicNo.
     * @param value value to set the DrLicNo
     */
    public void setDrLicNo(String value) {
        setAttributeInternal(DRLICNO, value);
    }

    /**
     * Gets the attribute value for Telephone, using the alias name Telephone.
     * @return the value of Telephone
     */
    public String getTelephone() {
        return (String) getAttributeInternal(TELEPHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Telephone.
     * @param value value to set the Telephone
     */
    public void setTelephone(String value) {
        setAttributeInternal(TELEPHONE, value);
    }

    /**
     * Gets the attribute value for Mobile, using the alias name Mobile.
     * @return the value of Mobile
     */
    public String getMobile() {
        return (String) getAttributeInternal(MOBILE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Mobile.
     * @param value value to set the Mobile
     */
    public void setMobile(String value) {
        setAttributeInternal(MOBILE, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for Url, using the alias name Url.
     * @return the value of Url
     */
    public String getUrl() {
        return (String) getAttributeInternal(URL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Url.
     * @param value value to set the Url
     */
    public void setUrl(String value) {
        setAttributeInternal(URL, value);
    }

    /**
     * Gets the attribute value for PreAddress, using the alias name PreAddress.
     * @return the value of PreAddress
     */
    public String getPreAddress() {
        return (String) getAttributeInternal(PREADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreAddress.
     * @param value value to set the PreAddress
     */
    public void setPreAddress(String value) {
        setAttributeInternal(PREADDRESS, value);
    }

    /**
     * Gets the attribute value for PerAddress, using the alias name PerAddress.
     * @return the value of PerAddress
     */
    public String getPerAddress() {
        return (String) getAttributeInternal(PERADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PerAddress.
     * @param value value to set the PerAddress
     */
    public void setPerAddress(String value) {
        setAttributeInternal(PERADDRESS, value);
    }

    /**
     * Gets the attribute value for Image, using the alias name Image.
     * @return the value of Image
     */
    public String getImage() {
        return (String) getAttributeInternal(IMAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Image.
     * @param value value to set the Image
     */
    public void setImage(String value) {
        setAttributeInternal(IMAGE, value);
    }

    /**
     * Gets the attribute value for FarmerNo, using the alias name FarmerNo.
     * @return the value of FarmerNo
     */
    public String getFarmerNo() {
        return (String) getAttributeInternal(FARMERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FarmerNo.
     * @param value value to set the FarmerNo
     */
    public void setFarmerNo(String value) {
        setAttributeInternal(FARMERNO, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for FarmerRegTehsil, using the alias name FarmerRegTehsil.
     * @return the value of FarmerRegTehsil
     */
    public BigDecimal getFarmerRegTehsil() {
        return (BigDecimal) getAttributeInternal(FARMERREGTEHSIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for FarmerRegTehsil.
     * @param value value to set the FarmerRegTehsil
     */
    public void setFarmerRegTehsil(BigDecimal value) {
        setAttributeInternal(FARMERREGTEHSIL, value);
    }

    /**
     * Gets the attribute value for FarmerRegDistrict, using the alias name FarmerRegDistrict.
     * @return the value of FarmerRegDistrict
     */
    public BigDecimal getFarmerRegDistrict() {
        return (BigDecimal) getAttributeInternal(FARMERREGDISTRICT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FarmerRegDistrict.
     * @param value value to set the FarmerRegDistrict
     */
    public void setFarmerRegDistrict(BigDecimal value) {
        setAttributeInternal(FARMERREGDISTRICT, value);
    }

    /**
     * Gets the attribute value for GrantStatus, using the alias name GrantStatus.
     * @return the value of GrantStatus
     */
    public String getGrantStatus() {
        return (String) getAttributeInternal(GRANTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantStatus.
     * @param value value to set the GrantStatus
     */
    public void setGrantStatus(String value) {
        setAttributeInternal(GRANTSTATUS, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMmpFarmerRegVerifLand() {
        return (RowIterator) getAttributeInternal(MMPFARMERREGVERIFLAND);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMmpFarmerRegDVerif() {
        return (RowIterator) getAttributeInternal(MMPFARMERREGDVERIF);
    }

    /**
     * @param farmerRegVerifId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal farmerRegVerifId) {
        return new Key(new Object[] { farmerRegVerifId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.MmpFarmerRegVerif");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
         try {
             loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
             } else if(operation == DML_UPDATE) {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

