package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 06 17:09:32 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MmpMonSchMasterImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MmpMonSchMasterId,
        MmpPhaseId,
        Dated,
        MemberRegId,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        MmpMemberReg,
        MmpMonSchDetail,
        TblPhase;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MMPMONSCHMASTERID = AttributesEnum.MmpMonSchMasterId.index();
    public static final int MMPPHASEID = AttributesEnum.MmpPhaseId.index();
    public static final int DATED = AttributesEnum.Dated.index();
    public static final int MEMBERREGID = AttributesEnum.MemberRegId.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int MMPMEMBERREG = AttributesEnum.MmpMemberReg.index();
    public static final int MMPMONSCHDETAIL = AttributesEnum.MmpMonSchDetail.index();
    public static final int TBLPHASE = AttributesEnum.TblPhase.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MmpMonSchMasterImpl() {
    }

    /**
     * Gets the attribute value for MmpMonSchMasterId, using the alias name MmpMonSchMasterId.
     * @return the value of MmpMonSchMasterId
     */
    public BigDecimal getMmpMonSchMasterId() {
        return (BigDecimal) getAttributeInternal(MMPMONSCHMASTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpMonSchMasterId.
     * @param value value to set the MmpMonSchMasterId
     */
    public void setMmpMonSchMasterId(BigDecimal value) {
        setAttributeInternal(MMPMONSCHMASTERID, value);
    }

    /**
     * Gets the attribute value for MmpPhaseId, using the alias name MmpPhaseId.
     * @return the value of MmpPhaseId
     */
    public BigDecimal getMmpPhaseId() {
        return (BigDecimal) getAttributeInternal(MMPPHASEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpPhaseId.
     * @param value value to set the MmpPhaseId
     */
    public void setMmpPhaseId(BigDecimal value) {
        setAttributeInternal(MMPPHASEID, value);
    }

    /**
     * Gets the attribute value for Dated, using the alias name Dated.
     * @return the value of Dated
     */
    public Timestamp getDated() {
        return (Timestamp) getAttributeInternal(DATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dated.
     * @param value value to set the Dated
     */
    public void setDated(Timestamp value) {
        setAttributeInternal(DATED, value);
    }

    /**
     * Gets the attribute value for MemberRegId, using the alias name MemberRegId.
     * @return the value of MemberRegId
     */
    public BigDecimal getMemberRegId() {
        return (BigDecimal) getAttributeInternal(MEMBERREGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MemberRegId.
     * @param value value to set the MemberRegId
     */
    public void setMemberRegId(BigDecimal value) {
        setAttributeInternal(MEMBERREGID, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @return the associated entity MmpMemberRegImpl.
     */
    public MmpMemberRegImpl getMmpMemberReg() {
        return (MmpMemberRegImpl) getAttributeInternal(MMPMEMBERREG);
    }

    /**
     * Sets <code>value</code> as the associated entity MmpMemberRegImpl.
     */
    public void setMmpMemberReg(MmpMemberRegImpl value) {
        setAttributeInternal(MMPMEMBERREG, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMmpMonSchDetail() {
        return (RowIterator) getAttributeInternal(MMPMONSCHDETAIL);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTblPhase() {
        return (EntityImpl) getAttributeInternal(TBLPHASE);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTblPhase(EntityImpl value) {
        setAttributeInternal(TBLPHASE, value);
    }

    /**
     * @param mmpMonSchMasterId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal mmpMonSchMasterId) {
        return new Key(new Object[] { mmpMonSchMasterId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.MmpMonSchMaster");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
         try {
             loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
             } else if(operation == DML_UPDATE) {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

