package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 07 12:52:41 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MmpRoleDetailPagesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MmpRoleDetailPagesId,
        MmpRoleMasterId,
        MmpPagesId,
        MmpRView,
        MmpRAdd,
        MmpREdit,
        MmpRDelete,
        MmpRPrint,
        MmpRPost,
        MmpRoleDetailModulesId,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        MmpRoleMaster;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MMPROLEDETAILPAGESID = AttributesEnum.MmpRoleDetailPagesId.index();
    public static final int MMPROLEMASTERID = AttributesEnum.MmpRoleMasterId.index();
    public static final int MMPPAGESID = AttributesEnum.MmpPagesId.index();
    public static final int MMPRVIEW = AttributesEnum.MmpRView.index();
    public static final int MMPRADD = AttributesEnum.MmpRAdd.index();
    public static final int MMPREDIT = AttributesEnum.MmpREdit.index();
    public static final int MMPRDELETE = AttributesEnum.MmpRDelete.index();
    public static final int MMPRPRINT = AttributesEnum.MmpRPrint.index();
    public static final int MMPRPOST = AttributesEnum.MmpRPost.index();
    public static final int MMPROLEDETAILMODULESID = AttributesEnum.MmpRoleDetailModulesId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int MMPROLEMASTER = AttributesEnum.MmpRoleMaster.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MmpRoleDetailPagesImpl() {
    }

    /**
     * Gets the attribute value for MmpRoleDetailPagesId, using the alias name MmpRoleDetailPagesId.
     * @return the value of MmpRoleDetailPagesId
     */
    public BigDecimal getMmpRoleDetailPagesId() {
        return (BigDecimal) getAttributeInternal(MMPROLEDETAILPAGESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRoleDetailPagesId.
     * @param value value to set the MmpRoleDetailPagesId
     */
    public void setMmpRoleDetailPagesId(BigDecimal value) {
        setAttributeInternal(MMPROLEDETAILPAGESID, value);
    }

    /**
     * Gets the attribute value for MmpRoleMasterId, using the alias name MmpRoleMasterId.
     * @return the value of MmpRoleMasterId
     */
    public BigDecimal getMmpRoleMasterId() {
        return (BigDecimal) getAttributeInternal(MMPROLEMASTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRoleMasterId.
     * @param value value to set the MmpRoleMasterId
     */
    public void setMmpRoleMasterId(BigDecimal value) {
        setAttributeInternal(MMPROLEMASTERID, value);
    }

    /**
     * Gets the attribute value for MmpPagesId, using the alias name MmpPagesId.
     * @return the value of MmpPagesId
     */
    public BigDecimal getMmpPagesId() {
        return (BigDecimal) getAttributeInternal(MMPPAGESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpPagesId.
     * @param value value to set the MmpPagesId
     */
    public void setMmpPagesId(BigDecimal value) {
        setAttributeInternal(MMPPAGESID, value);
    }

    /**
     * Gets the attribute value for MmpRView, using the alias name MmpRView.
     * @return the value of MmpRView
     */
    public String getMmpRView() {
        return (String) getAttributeInternal(MMPRVIEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRView.
     * @param value value to set the MmpRView
     */
    public void setMmpRView(String value) {
        setAttributeInternal(MMPRVIEW, value);
    }

    /**
     * Gets the attribute value for MmpRAdd, using the alias name MmpRAdd.
     * @return the value of MmpRAdd
     */
    public String getMmpRAdd() {
        return (String) getAttributeInternal(MMPRADD);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRAdd.
     * @param value value to set the MmpRAdd
     */
    public void setMmpRAdd(String value) {
        setAttributeInternal(MMPRADD, value);
    }

    /**
     * Gets the attribute value for MmpREdit, using the alias name MmpREdit.
     * @return the value of MmpREdit
     */
    public String getMmpREdit() {
        return (String) getAttributeInternal(MMPREDIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpREdit.
     * @param value value to set the MmpREdit
     */
    public void setMmpREdit(String value) {
        setAttributeInternal(MMPREDIT, value);
    }

    /**
     * Gets the attribute value for MmpRDelete, using the alias name MmpRDelete.
     * @return the value of MmpRDelete
     */
    public String getMmpRDelete() {
        return (String) getAttributeInternal(MMPRDELETE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRDelete.
     * @param value value to set the MmpRDelete
     */
    public void setMmpRDelete(String value) {
        setAttributeInternal(MMPRDELETE, value);
    }

    /**
     * Gets the attribute value for MmpRPrint, using the alias name MmpRPrint.
     * @return the value of MmpRPrint
     */
    public String getMmpRPrint() {
        return (String) getAttributeInternal(MMPRPRINT);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRPrint.
     * @param value value to set the MmpRPrint
     */
    public void setMmpRPrint(String value) {
        setAttributeInternal(MMPRPRINT, value);
    }

    /**
     * Gets the attribute value for MmpRPost, using the alias name MmpRPost.
     * @return the value of MmpRPost
     */
    public String getMmpRPost() {
        return (String) getAttributeInternal(MMPRPOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRPost.
     * @param value value to set the MmpRPost
     */
    public void setMmpRPost(String value) {
        setAttributeInternal(MMPRPOST, value);
    }

    /**
     * Gets the attribute value for MmpRoleDetailModulesId, using the alias name MmpRoleDetailModulesId.
     * @return the value of MmpRoleDetailModulesId
     */
    public BigDecimal getMmpRoleDetailModulesId() {
        return (BigDecimal) getAttributeInternal(MMPROLEDETAILMODULESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRoleDetailModulesId.
     * @param value value to set the MmpRoleDetailModulesId
     */
    public void setMmpRoleDetailModulesId(BigDecimal value) {
        setAttributeInternal(MMPROLEDETAILMODULESID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getMmpRoleMaster() {
        return (EntityImpl) getAttributeInternal(MMPROLEMASTER);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setMmpRoleMaster(EntityImpl value) {
        setAttributeInternal(MMPROLEMASTER, value);
    }

    /**
     * @param mmpRoleDetailPagesId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal mmpRoleDetailPagesId) {
        return new Key(new Object[] { mmpRoleDetailPagesId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.MmpRoleDetailPages");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
         try {
             loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
             } else if(operation == DML_UPDATE) {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

