package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 07 12:50:59 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MmpRoleDetailModulesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MmpRoleDetailModulesId,
        MmpRoleMasterId,
        MmpModuleMenuId,
        MmpRView,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        MmpRoleMaster;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MMPROLEDETAILMODULESID = AttributesEnum.MmpRoleDetailModulesId.index();
    public static final int MMPROLEMASTERID = AttributesEnum.MmpRoleMasterId.index();
    public static final int MMPMODULEMENUID = AttributesEnum.MmpModuleMenuId.index();
    public static final int MMPRVIEW = AttributesEnum.MmpRView.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int MMPROLEMASTER = AttributesEnum.MmpRoleMaster.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MmpRoleDetailModulesImpl() {
    }

    /**
     * Gets the attribute value for MmpRoleDetailModulesId, using the alias name MmpRoleDetailModulesId.
     * @return the value of MmpRoleDetailModulesId
     */
    public BigDecimal getMmpRoleDetailModulesId() {
        return (BigDecimal) getAttributeInternal(MMPROLEDETAILMODULESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRoleDetailModulesId.
     * @param value value to set the MmpRoleDetailModulesId
     */
    public void setMmpRoleDetailModulesId(BigDecimal value) {
        setAttributeInternal(MMPROLEDETAILMODULESID, value);
    }

    /**
     * Gets the attribute value for MmpRoleMasterId, using the alias name MmpRoleMasterId.
     * @return the value of MmpRoleMasterId
     */
    public BigDecimal getMmpRoleMasterId() {
        return (BigDecimal) getAttributeInternal(MMPROLEMASTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRoleMasterId.
     * @param value value to set the MmpRoleMasterId
     */
    public void setMmpRoleMasterId(BigDecimal value) {
        setAttributeInternal(MMPROLEMASTERID, value);
    }

    /**
     * Gets the attribute value for MmpModuleMenuId, using the alias name MmpModuleMenuId.
     * @return the value of MmpModuleMenuId
     */
    public BigDecimal getMmpModuleMenuId() {
        return (BigDecimal) getAttributeInternal(MMPMODULEMENUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpModuleMenuId.
     * @param value value to set the MmpModuleMenuId
     */
    public void setMmpModuleMenuId(BigDecimal value) {
        setAttributeInternal(MMPMODULEMENUID, value);
    }

    /**
     * Gets the attribute value for MmpRView, using the alias name MmpRView.
     * @return the value of MmpRView
     */
    public String getMmpRView() {
        return (String) getAttributeInternal(MMPRVIEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpRView.
     * @param value value to set the MmpRView
     */
    public void setMmpRView(String value) {
        setAttributeInternal(MMPRVIEW, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getMmpRoleMaster() {
        return (EntityImpl) getAttributeInternal(MMPROLEMASTER);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setMmpRoleMaster(EntityImpl value) {
        setAttributeInternal(MMPROLEMASTER, value);
    }

    /**
     * @param mmpRoleDetailModulesId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal mmpRoleDetailModulesId) {
        return new Key(new Object[] { mmpRoleDetailModulesId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.MmpRoleDetailModules");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
         try {
             loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
             } else if(operation == DML_UPDATE) {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

