package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 06 17:13:55 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MmpTrainingCheckInImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MmpTrainingCheckInId,
        ClusterId,
        Dated,
        TrainingStarted,
        Remarks,
        Latitude,
        Longitude,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        MemberRegId,
        TrainingSchDetailId,
        MmpMonSchDetailId,
        TblCluster,
        MmpMonSchDetail,
        MmpTrainingMonInsp;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int MMPTRAININGCHECKINID = AttributesEnum.MmpTrainingCheckInId.index();
    public static final int CLUSTERID = AttributesEnum.ClusterId.index();
    public static final int DATED = AttributesEnum.Dated.index();
    public static final int TRAININGSTARTED = AttributesEnum.TrainingStarted.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LATITUDE = AttributesEnum.Latitude.index();
    public static final int LONGITUDE = AttributesEnum.Longitude.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int MEMBERREGID = AttributesEnum.MemberRegId.index();
    public static final int TRAININGSCHDETAILID = AttributesEnum.TrainingSchDetailId.index();
    public static final int MMPMONSCHDETAILID = AttributesEnum.MmpMonSchDetailId.index();
    public static final int TBLCLUSTER = AttributesEnum.TblCluster.index();
    public static final int MMPMONSCHDETAIL = AttributesEnum.MmpMonSchDetail.index();
    public static final int MMPTRAININGMONINSP = AttributesEnum.MmpTrainingMonInsp.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MmpTrainingCheckInImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.MmpTrainingCheckIn");
    }


    /**
     * Gets the attribute value for MmpTrainingCheckInId, using the alias name MmpTrainingCheckInId.
     * @return the value of MmpTrainingCheckInId
     */
    public BigDecimal getMmpTrainingCheckInId() {
        return (BigDecimal) getAttributeInternal(MMPTRAININGCHECKINID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpTrainingCheckInId.
     * @param value value to set the MmpTrainingCheckInId
     */
    public void setMmpTrainingCheckInId(BigDecimal value) {
        setAttributeInternal(MMPTRAININGCHECKINID, value);
    }

    /**
     * Gets the attribute value for ClusterId, using the alias name ClusterId.
     * @return the value of ClusterId
     */
    public BigDecimal getClusterId() {
        return (BigDecimal) getAttributeInternal(CLUSTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClusterId.
     * @param value value to set the ClusterId
     */
    public void setClusterId(BigDecimal value) {
        setAttributeInternal(CLUSTERID, value);
    }

    /**
     * Gets the attribute value for Dated, using the alias name Dated.
     * @return the value of Dated
     */
    public Timestamp getDated() {
        return (Timestamp) getAttributeInternal(DATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dated.
     * @param value value to set the Dated
     */
    public void setDated(Timestamp value) {
        setAttributeInternal(DATED, value);
    }

    /**
     * Gets the attribute value for TrainingStarted, using the alias name TrainingStarted.
     * @return the value of TrainingStarted
     */
    public String getTrainingStarted() {
        return (String) getAttributeInternal(TRAININGSTARTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrainingStarted.
     * @param value value to set the TrainingStarted
     */
    public void setTrainingStarted(String value) {
        setAttributeInternal(TRAININGSTARTED, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Latitude, using the alias name Latitude.
     * @return the value of Latitude
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) getAttributeInternal(LATITUDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Latitude.
     * @param value value to set the Latitude
     */
    public void setLatitude(BigDecimal value) {
        setAttributeInternal(LATITUDE, value);
    }

    /**
     * Gets the attribute value for Longitude, using the alias name Longitude.
     * @return the value of Longitude
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) getAttributeInternal(LONGITUDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Longitude.
     * @param value value to set the Longitude
     */
    public void setLongitude(BigDecimal value) {
        setAttributeInternal(LONGITUDE, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for MemberRegId, using the alias name MemberRegId.
     * @return the value of MemberRegId
     */
    public BigDecimal getMemberRegId() {
        return (BigDecimal) getAttributeInternal(MEMBERREGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MemberRegId.
     * @param value value to set the MemberRegId
     */
    public void setMemberRegId(BigDecimal value) {
        setAttributeInternal(MEMBERREGID, value);
    }

    /**
     * Gets the attribute value for TrainingSchDetailId, using the alias name TrainingSchDetailId.
     * @return the value of TrainingSchDetailId
     */
    public BigDecimal getTrainingSchDetailId() {
        return (BigDecimal) getAttributeInternal(TRAININGSCHDETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrainingSchDetailId.
     * @param value value to set the TrainingSchDetailId
     */
    public void setTrainingSchDetailId(BigDecimal value) {
        setAttributeInternal(TRAININGSCHDETAILID, value);
    }

    /**
     * Gets the attribute value for MmpMonSchDetailId, using the alias name MmpMonSchDetailId.
     * @return the value of MmpMonSchDetailId
     */
    public BigDecimal getMmpMonSchDetailId() {
        return (BigDecimal) getAttributeInternal(MMPMONSCHDETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MmpMonSchDetailId.
     * @param value value to set the MmpMonSchDetailId
     */
    public void setMmpMonSchDetailId(BigDecimal value) {
        setAttributeInternal(MMPMONSCHDETAILID, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTblCluster() {
        return (EntityImpl) getAttributeInternal(TBLCLUSTER);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTblCluster(EntityImpl value) {
        setAttributeInternal(TBLCLUSTER, value);
    }


    /**
     * @return the associated entity MmpMonSchDetailImpl.
     */
    public MmpMonSchDetailImpl getMmpMonSchDetail() {
        return (MmpMonSchDetailImpl) getAttributeInternal(MMPMONSCHDETAIL);
    }

    /**
     * Sets <code>value</code> as the associated entity MmpMonSchDetailImpl.
     */
    public void setMmpMonSchDetail(MmpMonSchDetailImpl value) {
        setAttributeInternal(MMPMONSCHDETAIL, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMmpTrainingMonInsp() {
        return (RowIterator) getAttributeInternal(MMPTRAININGMONINSP);
    }


    /**
     * @param mmpTrainingCheckInId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal mmpTrainingCheckInId) {
        return new Key(new Object[] { mmpTrainingCheckInId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
           try {
               loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
           } catch(Exception ex) {
               ex.printStackTrace();
           }
           
           if (operation == DML_INSERT) {
               setCreatedBy(loginId);
               setUpdatedBy(loginId);
               } else if(operation == DML_UPDATE) {
               setUpdatedBy(loginId);
           }
        super.doDML(operation, e);
    }
}

